routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/neworg', function () {
    return view('auth.registeror');
})->name('neworg');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('meetings', 'MeetingController')->middleware('auth');


Route::post('meetings/todo/{id}', 'MeetingController@add_todo')->name('meetings.add_todo');
Route::get('meetings/create_todo/{mid}', 'MeetingController@create_todo')->name('meetings.create_todo');


Route::get('meetings/spmeet/{id}', 'MeetingController@spmeet')->name('meetings.spmeet');

Route::get('meetings/dash/{id}', 'MeetingController@dash')->name('meetings.dash');

Route::get('meetings/edittopic/{id}', 'MeetingController@edittopic')->name('meetings.edittopic');
Route::patch('meetings/updatetopic/{id}', 'MeetingController@updatetopic')->name('meetings.updatetopic');

Route::get('meetings/edittodo/{id}', 'MeetingController@edittodo')->name('meetings.edittodo');
Route::patch('meetings/updatetodo/{id}', 'MeetingController@updatetodo')->name('meetings.updatetodo');


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::put('profile/org', ['as' => 'profile.org', 'uses' => 'ProfileController@org']);
});

app/Meeting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meeting extends Model
{

    protected $fillable = [
        'title', 'location', 'date', 'hour',

    ];
    protected $casts = [
        'hour' => 'hh:mm',
        'hend' => 'hh:mm',
    ];
    public function user(){
        return $this->belongsTo(User::class);
    }
    public function participants()
    {
        return $this->hasMany('App\Participant');
    }

}

app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Gate; 
use App\Meeting;
use App\Topic;
use App\Participant;
use App\Todo;
use App\Organization;
use Charts; 
class MeetingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Gate::allows('admin')){
            $id= Auth::id();
            $user2 = User::find($id);
            $numorg = $user2->organization_id;
            $meetings2 = DB::table('meetings')
                ->join('users', 'meetings.user_id', '=', 'users.id')
                ->select('meetings.*')->where('users.organization_id',$numorg)
                ;
            $meetings = DB::table('meetings')
                ->join('participants', 'meetings.id', '=', 'participants.meeting_id')
                ->select('meetings.*')->where('participants.user_id',$id)
                ->union($meetings2)
                ->get();
                return view('meetings.index',['meetings'=>$meetings]);
        }
        if(Gate::allows('employee') || Gate::allows('manager')){
            $id= Auth::id();
            $meetings = DB::table('meetings')
                ->join('participants', 'meetings.id', '=', 'participants.meeting_id')
                ->select('meetings.*')->where('participants.user_id',$id)
                ->get();
            return view('meetings.index',['meetings'=>$meetings]);    
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        if(Gate::allows('admin') || Gate::allows('manager')){
            $id= Auth::id();
            $user = DB::table('users')->where('id','!=',$id)->get();

            return view('meetings.create',['users'=>$user]);
        }else{
            abort(403,'Sorry you are not allow to crate meetings...');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Gate::denies('admin') || Gate::denies('manager')){
            $id= Auth::id();
            $user2 = User::find($id);
            $numorg = $user2->organization_id;
            $mintopic = DB::table('organizations')->where('id', $numorg)->value('mintopic');
            $this->validate($request,[
                'topic_title' =>"required|array|min:$mintopic",
                'hend' => "after:hour",
                'topic_hour.*' => "after:hour|before:hend",
                'date' => "after:today",
            ]);
            
            
            $meeting = new Meeting();
            $id = Auth::id();
            $meeting->title = $request->name;
            $meeting->user_id = $id;
            $meeting->location = $request->location;
            $meeting->date = $request->date;
            $meeting->hour = $request->hour;
            $meeting->hend = $request->hend;
            $meeting->save();
            
            $mid = $meeting->id;
            $topic_title = $request->input('topic_title');
            $topic_hour = $request->input('topic_hour');
            for ($i=0; $i <count($topic_title) ; $i++) { 
                $topic = new Topic();
                $topic->topic_title = $topic_title[$i];
                $topic->topic_hour = $topic_hour[$i];
                $topic->meeting_id = $mid;
                $topic->status = 0;
                $topic->save();
            }
            $part = new Participant();
            $part->user_id =$id;
            $part->meeting_id = $mid;
            $part->save();  

            $participants = $request->input('participants');
            for ($i=0; $i < count($participants) ; $i++) { 
                $participant = new Participant();
                $participant->user_id = $participants[$i];
                $participant->meeting_id = $mid;
                $participant->save();
            }
        
            
            return redirect('meetings');

        }else{
            abort(403,'Are you hacker or what?');
        }
       
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Gate::allows('admin') || Gate::allows('manager')){
            $meeting = Meeting::find($id);
            return view('meetings.edit',compact('meeting'));
        }else{
            abort(403,'Are you hacker or what?');
        }
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Gate::allows('admin') || Gate::allows('manager')){
            $meeting = Meeting::find($id);
            $this->validate($request,[
                'hend' => "after:hour",
                'date' => "after:today",
            ]);
            $meeting->update($request->all());    
            return redirect('meetings');
        }else{
            abort(403,'Are you hacker or what?');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Gate::allows('admin') || Gate::allows('manager')){
            $meeting = Meeting::find($id);
            $meeting ->delete();
            
            $meeting_id = $id;
            $topic = Topic::where('meeting_id',$id);
                $topic ->delete();
            $participant = Participant::where('meeting_id',$id);
                $participant ->delete(); 
            
            return redirect('meetings');
        }else{
            abort(403,'Are you hacker or what?');
        }
    }

    public function create_todo($mid)
    {
        if(Gate::allows('admin') || Gate::allows('manager')){
            $part = DB::table('participants')
            ->join('users', 'participants.user_id', '=', 'users.id')
            ->select('users.name','users.id','participants.meeting_id')->where('participants.meeting_id',$mid)
            ->get();
            return view('meetings.createtodo',['parts'=>$part]);
        }else{
            abort(403,'Sorry you are not allow to crate todos...');
        }

    }

    public function add_todo($mid,Request $request)
    {
        if(Gate::allows('admin') || Gate::allows('manager')){
            $this->validate($request,[
                'due_date' => "after:today",
            ]);
            $todo = new Todo;
            $todo->title = $request->title;
            $todo->status = 0; 
            $todo->user_id = $request->user_id;
            $todo->meeting_id = $mid;
            $todo->due_date = $request->due_date;
            $todo->save();
            return redirect('meetings');
        }else{
            abort(403,'Are you hacker or what?');
        }

    }

    public function spmeet($mid,Request $request)
    {
        
        //$topics = DB::table('topics')->where('meeting_id', $mid)->get(); 
        $id= Auth::id();
        $topics = DB::table('meetings')
            ->join('topics', 'meetings.id', '=', 'topics.meeting_id')
            ->select('topics.*','meetings.hour','meetings.hend','meetings.date')->where('topics.meeting_id',$mid)
            ->get();
        if(Gate::allows('employee')){
            $todos = DB::table('todos')->where([
                ['meeting_id', $mid],
                ['user_id',$id]
                ])->get();
        }else{
            $todos = DB::table('todos')->where('meeting_id', $mid)->get();
        }
       

        return view('meetings.spmeet',['topics'=>$topics,'todos'=>$todos]);
    }

    public function edittopic($id)
    {
        if(Gate::allows('admin') || Gate::allows('manager')){
            $topic = Topic::find($id);
            $id= Auth::id();
            $allmeeting = DB::table('meetings')->where('user_id', $id)->get(); 
            return view('meetings.edittopic',compact('topic',"allmeeting"));
        }else{
            abort(403,'Are you hacker or what?');
        }
    }

    public function updatetopic(Request $request, $id)
    {
        if(Gate::allows('admin') || Gate::allows('manager')){
            
            $topic = Topic::find($id);
            $time = DB::table('topics')
            ->join('meetings','topics.meeting_id','=','meetings.id')
            ->select('meetings.hour','meetings.hend')
            ->where('topics.id',$id)->get();
            foreach ($time as $times) {
                $sh = $times->hour;
                $eh = $times->hend;
            };
            //die($eh);
            $this->validate($request,[
                'topic_hour' => "after:$sh|before:$eh",
                
            ]);
               
            $topic->update($request->all());
            $topic->update($request ->except(['_token']));
            if($request->ajax()){
                return Response::json(array('result'=>'success','status'=>$request->status),200);    
               }    
            return redirect('meetings');
        }else{
            abort(403,'Are you hacker or what?');
        }
    }

    public function edittodo($id)
    {
        if(Gate::allows('admin') || Gate::allows('manager')){
            $todo = Todo::find($id);
            return view('meetings.edittodo',compact('todo'));
        }else{

resources/views/meetings/create.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Create a new meeting') }}</h3>
                            </div>
                            
                        </div>
                    </div>
                    <div id="box">
                    
                    <div class = "col-md-5">
                    <div class = "container">
                    <form method="post" action="{{ action('MeetingController@store') }}" autocomplete="on">
                            @csrf
                            

                            <div class="pl-lg-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="name">{{ __('Name of the meeting') }}</label>
                                    <input type="text" name="name"  class="form-control form-control-alternative" placeholder="{{ __('Name of the meeting') }}" value="" required>
                                </div>
                                
                                <div class="form-group">
                                    <label class="form-control-label" for="location">{{ __('Location of the meeting') }}</label>
                                    <input type="datetime" name="location"  class="form-control form-control-alternative" placeholder="{{ __('Location of the meeting') }}" value="" required>
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="date">{{ __('Date of the meeting') }}</label>
                                    <input type="date" name="date"  class="form-control form-control-alternative" placeholder="{{ __('Date  of the meeting') }}" value="" required>
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="hour">{{ __('Hour of the meeting') }}</label>
                                    <input type="time" name="hour"  class="form-control form-control-alternative" placeholder="{{ __('Hour of the meeting') }}" value="" required>
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="hend">{{ __('End hour of the meeting') }}</label>
                                    <input type="time" name="hend"  class="form-control form-control-alternative" placeholder="{{ __('End hour of the meeting') }}" value="" required>
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="participants">{{ __('Participants') }}</label>
                                    <select class="form-control m-bot15" name="participants[]" class="form-control form-control-alternative" placeholder="{{ __('Participants of the meeting') }}" value="" required>
                                    @foreach($users as $user)   
                                        <option value="{{ $user->id }}" {{ $selectedRole = $user->id ? 'selected="selected"' : '' }}>{{ $user->email }}</option> 
                                    @endforeach
                                    </select>
                                </div>
                                
                                <div id='participants'>

                                </div>

                                <div  id ="addp">
                                <a class="btn btn-info mt-2" >{{ __('Add participants') }}</a>
                                 </div><br>

                                <div class="form-group">
                                    <label class="form-control-label" for="topic_title">{{ __('Topics') }}</label>
                                    <input type="text" name="topic_title[]"  class="form-control form-control-alternative" placeholder="{{ __('Topics of the meeting') }}" value="" required><br>
                                    <input type="time" name="topic_hour[]"  class="form-control form-control-alternative"  value="" required>

                                </div>
                                

                                <div id='topics'>

                                </div>
                                <div  id ="add">
                                <a class="btn btn-info mt-2" >{{ __('Add topic') }}</a>
                                 </div>

                                 @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                 

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4" value="Save">{{ __('Create') }}</button>
                                </div>
                            </div>
                        </form>
                     </div>
                     </div>
                     </div>
                    
                    
                    
                </div>
            </div>
        </div>

        <script>

                function createTicketComponent(type) {
                type = type || null;
                
                var elements   = [],
                    rootElement = document.createElement('p');
                        
                elements.push('<label class="form-control-label" for="topic">{{ __('Topics') }}</label><input type="text" name="topic_title[]"  class="form-control form-control-alternative" placeholder="{{ __('Topics of the meeting') }}" value="" required><br>');
                elements.push('<input type="time" name="topic_hour[]"  class="form-control form-control-alternative"  value="" required><br>');
                
                    
                rootElement.innerHTML = elements.join('');
                
                return rootElement;
                }

                function createTicketComponent2(type) {
                type = type || null;
                
                var elements   = [],
                    rootElement = document.createElement('p');
                        
                elements.push('<label class="form-control-label" for="participants">{{ __('Participants') }}</label>');
                elements.push('<select class="form-control m-bot15" name="participants[]" class="form-control form-control-alternative" placeholder="{{ __('Participants of the meeting') }}" value="" required>@foreach($users as $user)<option value="{{ $user->id }}" {{ $selectedRole = $user->id ? 'selected="selected"' : '' }}>{{ $user->email }}</option> @endforeach</select><br>');
                
                    
                rootElement.innerHTML = elements.join('');
                
                return rootElement;
                }

              


                function onClickCreateTicketButton(event) {
                var button    = event.target,
                    container = document.querySelector('#topics'),
                    component;

                
                    component = createTicketComponent();
                

                container.appendChild(component);
                }

                function onClickCreateTicketButton2(event) {
                var button    = event.target,
                    container = document.querySelector('#participants'),
                    component;

                
                    component = createTicketComponent2();
                

                container.appendChild(component);
                }

                
                var buttonsGroup = document.getElementById('add');
                buttonsGroup.addEventListener('click', onClickCreateTicketButton);
                var buttonsGroup2 = document.getElementById('addp');
                buttonsGroup2.addEventListener('click', onClickCreateTicketButton2);


</script>
            
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/meetings/createtodo.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Create a new Todo') }}</h3>
                            </div>
                            
                        </div>
                    </div>
                    
                    
                    <div class = "col-md-5">
                    <div class = "container">
                    <form method="post" action="{{route('meetings.add_todo', Request::segment(3)  )}}" autocomplete="on">
                            @csrf
                            

                            <div class="pl-lg-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="title">{{ __('Name of the todo') }}</label>
                                    <input type="text" name="title"  class="form-control form-control-alternative" placeholder="{{ __('Name of the todo') }}" value="" required>
                                </div>
                            </div>

                            <div class="pl-lg-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="due_date">{{ __('Due Date') }}</label>
                                    <input type="date" name="due_date"  class="form-control form-control-alternative" placeholder="{{ __('Due Date') }}" value="" required>
                                </div>
                            </div>

                            <div class="pl-lg-4">
                            <div class="form-group">
                                    <label class="form-control-label" for="user_id">{{ __('Participants') }}</label>
                                    <select class="form-control m-bot15" name="user_id" class="form-control form-control-alternative" placeholder="{{ __('User to perform') }}" value="" required>
                                    @foreach($parts as $part)   
                                        <option value="{{ $part->id }}" {{ $selectedRole = $part->id ? 'selected="selected"' : '' }}>{{ $part->name }}</option> 
                                    @endforeach
                                    </select>
                            </div>
                            </div>

                            @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif

                            <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4" value="Save">{{ __('Add') }}</button>
                            </div>
                                
                        </form>
                     </div>
                     </div>
                     
                    
                    
                    
                </div>
            </div>
        </div>
         
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/meetings/index.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

    
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Meetings') }}</h3>
                            </div>
                            @cannot('employee')<div class="col-4 text-right">
                                <a href="{{ route('meetings.create') }}" class="btn btn-sm btn-primary">{{ __('Add Meeting') }}</a>
                            </div> @endcannot
                        </div>
                    </div>
                    
                  

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Name') }}</th>
                                    <th scope="col">{{ __('Creator') }}</th>
                                    <th scope="col">{{ __('Date') }}</th>
                                    <th scope="col">{{ __('Hour') }}</th>
                                    <th scope="col">{{ __('Location') }}</th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                            @php $ndate = new DateTime('now');
                                    $nowdate = $ndate->format('Y-m-d');
                                 @endphp
                                @foreach ($meetings as $meeting)
                                    <tr>
                                        <td><a href = "{{route('meetings.spmeet',$meeting->id )}}"">{{ $meeting->title }}</a></td>
                                        <td>{{ $meeting->user_id }}</td>
                                        <td>{{ $meeting->date }}</td>
                                        <td>{{ $meeting->hour }}</td>
                                        <td>{{ $meeting->location }}</td>
                                        @cannot('employee')  <td>
                                        @if(strtotime($meeting->date) == strtotime($nowdate))
                                            @if(strtotime($meeting->hour) < time())
                                            <a href="{{route('meetings.create_todo',$meeting->id) }}">{{ __('Add Todo') }}</a>
                                            @endif
                                         @endif
                                         @if(strtotime($meeting->date) < strtotime($nowdate))
                                            <a href="{{route('meetings.create_todo',$meeting->id) }}">{{ __('Add Todo') }}</a>
                                        @endif </td>
                                        
                                        @endcannot

                                       @cannot('employee') <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                   
                                                        <form action="{{ route('meetings.destroy', $meeting->id) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            
                                                            <a class="dropdown-item" href="{{ route('meetings.edit', $meeting->id) }}">{{ __('Edit') }}</a>
                                                            <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this meeting?") }}') ? this.parentElement.submit() : ''">
                                                                {{ __('Delete') }}
                                                            </button>
                                                        </form>    
                                                    
                                                       
                                                </div>
                                            </div>
                                        </td>
                                        @endcannot
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection